### ISSUE TITLE
Integration with homebridge

### ISSUE THREAD

**Issue by jata1** [PSeitz/yamaha-nodejs#11]
Hi, 
I use homebridge https://github.com/nfarina/homebridge to control my Nest thermostat and also have the homebridge-yamaha https://github.com/neonightmare/homebridge-yamaha plugin working.

The problem is that the homebridge-yamaha plugin only supports basic commands (on/off and source on zone1) but I need it to support multi-zone, volume and source and it needs to work with homekit.

I'm not sure what I can do to help (i'm not a developer) but I think the options are:

1. further development of homebridge-yamaha to implement some of the functionality of yamaha-nodejs
2. development of yamaha-nodejs to interact with homebridge

I would like to know if there are other options and to understand the best (and easiest) way to progress this.

Any help or advice greatly appreciated.

**Comment by PSeitz** [comment]
yamaha-nodejs supports multiple zones. homebridge-yamaha is a wrapper around yamaha-nodejs to add support for homebridge, so option 1 is the way to go.
You can wait until someone resolves the issue or try it yourself ;)
https://github.com/neonightmare/homebridge-yamaha/issues/4

**Comment by jata1** [comment]
thanks for the link/info. 

Good to know that homebridge-yamaha already uses yamaha-nodejs but i'll have no chance of being able to do this myself. I'm amazed I even managed to get homebridge working at all. haha 

My brother is a developer so he might be able to help me.
