### ISSUE TITLE
Issue with OpenSSL between yams and alexandra install

### ISSUE THREAD

**Issue by sabolcik** [PSeitz/yamaha-nodejs#19]
Great little application which I have been able to get running with my alexa and my yamaha receiver.  Note that there is an error in the package installation of OpenSSL which I was able to work around.  I'm relatively new to python so I'm not sure if there is a way to update the installers to prevent it from occurring.

When you install yams the OpenSSL package that gets installed will fail with an error about an undefined environment variable.

The work around is to go into the python directory \Lib\site-packages and delete the OpenSSL and pyOpenSSL directories.  You then need to use pip to reinstall the pyOpenSSL package.  This resolved the issue on my machine.  

There is a second issue I had with Alexandra running on my windows PC.  It will attempt to parse the site certificate path from amazon and puke because the path after the server name doesn't match /echo.api/.  In util.py _get_certificate() I needed to change the  following line to remove the startswith statement.  I printed out the path and it was correct but apparently startswith doesn't parse the path correctly.  Might be a windows path issue.

    # Sanity check location so we don't get some random person's cert.
    if url.scheme != 'https' or \
       host not in ['s3.amazonaws.com', 's3.amazonaws.com:443'] or \
       **not path.startswith('/echo.api/'):** <- this fails
        log.error('invalid cert location %s - host %s - path %s', cert_url, host, path)
        return

Otherwise I'm digging it and was able to get everything running without too much pain for a python noob.

**Comment by PSeitz** [comment]
Hi, I'm not sure if this is the right project you are adressing, this is written in nodejs and not python.
Did you mean this: https://github.com/Raynes/yams?

**Comment by sabolcik** [comment]
Yeah - my bad...
