### ISSUE TITLE
delay is inserted regardless of PUT or GET

### ISSUE THREAD

**Issue by pbaggiol** [PSeitz/yamaha-nodejs#21]
The logic below is flawed.  isPutCommand always evaluates to true and the delay is always present even on GET.

var isPutCommand = xml.indexOf("cmd=\"PUT\"" >= 0);
var delay = isPutCommand ? this.responseDelay * 1000 : 0;

**Comment by PSeitz** [comment]
thanks for the bug report, I fixed this here https://github.com/PSeitz/yamaha-nodejs/commit/fb1d6341d267ce538eacfd473ffac8af974e7669

**Comment by PSeitz** [comment]
Published version `0.8.0` on npm
