### ISSUE TITLE
Scene Feature suggestion.

### ISSUE THREAD

**Issue by ArtemDyachuk** [PSeitz/yamaha-nodejs#24]
Hi 👋 

I'm working on homebridge-yamaha-home plugin. 
I've added scenes as inputs there. 
That plugin fully depends on yamaha-nodejs.

But I have found that there is no method to obtain scene information (at least scene name).
I have found some TCP commands in YNCA protocol, for example @MAIN:SCENENAME=?

What I'm trying to do is to convert it into xml request, and add new method to yamaha-nodejs functionality which can obtain information about scene.

But I'm not sure that I'm doing it in the right way.

May I ask for a bit of advice here? Thanks!

**Comment by PSeitz** [comment]
Hi,

easiest way is to go to the av receivers web interface (the receivers ip address) use the browser dev tools.
If there is a scene information displayed somewhere, you should be able to see the request in the requests tab.

**Comment by ArtemDyachuk** [comment]
Thanks for the advice.

I've checked everything and found XML "PUT" request. It puts the receiver into a scene number we specify. 

But in "GET" request after "PUT" there is no info about scene. Looks like receiver doesn't return any info about scene. 

Should I assume it's not possible then?

**EDIT**: I think it's possible but either not for all receivers or I have to find out how to use GET command: `@MAIN:SCENENAME=?` 

Here is from YNCA documentation:
```
SCENENAME [GET Command]
@MAIN:SCENENAME=?
Retrieving renamed info of all SCENE presets for Main Zone
```

**Comment by PSeitz** [comment]
If the scene info is shown somewhere in the ui, there is usually a request done before to get the info. 

I don't know if the different yamaha apis are completely mapped to each other, it could be that this info doesn't exist in the xml api.

**Comment by ArtemDyachuk** [comment]
In the web interface, there are 4 scene buttons. When I press any of them, it sends PUT request and selected scene turns on. But in web interface happens nothing. And GET response doesn't consist any info about the scene. 
I think it doesn't exist in XML. 

After checking YNCA documentation, I have found command that should get scene info. 
But it works through TCP connection. 
Also, I've seen python scripts here on github which probably can do that. But I'm not familiar with both python and TCP.

I'm just trying to find out am I missing something or just overthinking it. Or it's not possible to do.
