### ISSUE TITLE
NPM version doesn't match GitHub

### ISSUE THREAD

**Issue by NorthernMan54** [PSeitz/yamaha-nodejs#25]
@PSeitz I got a couple of bug reports and found that the version of the package on NPM doesn't match GitHub.  I think you need to publish in NPM.

Github has this on line 346 basicStatus.getZone = function() {

And NPM has this on 346     basicStatus.isOff = function() {

I think a NPM push is needed

**Comment by PSeitz** [comment]
I updated the version on npm to 0.9, the last PR wasn't published yet. Did you switch from the github repo as dependency to npm?

**Comment by NorthernMan54** [comment]
Yes, I switched as someone reported that the npm install of my code was failing on the GitHub repo.  I had seen that previously, and the easiest fix it to ensure you use the npm version.

I had used the GitHub version while I was waiting for the pull request last spring, and had never gone back and cleaned up.

**Comment by PSeitz** [comment]
Yeah, I forgot to push the stuff to npm, but it should work now.

**Comment by NorthernMan54** [comment]
Tks very much appreciated
