### ISSUE TITLE
Tailor to multiple zones

### ISSUE THREAD

**Issue by NovaGL** [PSeitz/yamaha-nodejs#3]
Not sure if anyone is updating this but this plugin seems tailored to one zone as most do, but I would like it to work will more than one I am happy to do a pull request.

Yamaha amps can go upto 4 zones as far as I know. I would like the word "Main Zone" replaced everywhere with a zone variable.

If that zone is not filled out it goes to "Main Zone" otherwise it goes to "Zone 2" 3 etc.

It makes it much more usable.

**Comment by 3space123** [comment]
+1 on this request!  However, @NovaGL, I just noticed that in the "PartyModeON/OFF" commit, there is the possibility to set Zones 1 through 4.  Am I reading this wrong?  I have an RX-A3040, and will play around with this, to see whether this works for that unit.  I'm guessing it will.

**Comment by NovaGL** [comment]
That is correct, Yamaha amps can have upto 4 zones meaning if you want to set zone 4 to AV4 you can now do it.

Like I said this is only the beginning and might be a better way to code it.

Let me know how you go, but I tested it myself and was able to change Zone2 to Pandora with no dramas.

At the moment Party Mode will only choose Zone 1 as the controller.

**Comment by 3space123** [comment]
Thanks for the response.  For a while, I got nothing on Home iOS app.  Then the Yamaha appeared (after maybe 1.5h?).  Anyway, now it seems like it goes to Spotify (as I wanted), but it seems like that's a canned function.  I can turn the Yamaha on and off, but that's it.  Do I need to add an "accessory" for each Yamaha function I want to perform?  Is it right that everything I need to do I can do in config.json in Homebridge (after issuing once the "sudo npm install -g Homebridge-Yamaha" , or do I need to go to npm and do something else?

**Comment by NovaGL** [comment]
I guess you are talking about the plugin for homebridge, this is not the repo for that.

That plugin doesn't have the functionality you want built in. You would need to add custom characteristics to do it, I never got around to it, because the plugin you are referring to relies on this changing being pulled, so there is no point. You can keep changing your config file but you won't get what you are after.

It might just be easier to use the homebridge http and use post commands. But we are getting way off-topic.

**Comment by 3space123** [comment]
@NovaGL: What do you meant by "changing being pulled"?  Thx!

**Comment by NovaGL** [comment]
I did a pull request to add additional features, for zones and party mode. Those features aren't in Homebridge-Yamaha. What you are asking is not possible at the moment.

**Comment by 3space123** [comment]
@NovaGL:  I wasn't sure whether this was linked with the Homebridge-yamaha or not.  That answers my question.  Thank you.
